#!/bin/bash

if [[ -z "$1" ]] || [[ ! -d "$(readlink -e "$1")" ]]; then
	echo "Usage: $0 DIRECTORY" &>2
	exit 1
fi

size=0
while read file; do
	size=$(($(cat "$file" | wc -c) + size))
done < <(find "$1" -type f)

echo "$size"
